language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

env:
  - ZIPKIN_PHP_VERSION=^1.3.6
  - ZIPKIN_PHP_VERSION=^2.0

jobs:
  exclude:
    - php: "5.6"
      env: ZIPKIN_PHP_VERSION=^2.0
    - php: "7.0"
      env: ZIPKIN_PHP_VERSION=^2.0

install:
  - composer require openzipkin/zipkin:"$ZIPKIN_PHP_VERSION"
  - composer install

script:
  - composer lint
  - composer test
